# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!

name:                hs-redis-clone
version:             0.1.0.0
license:             BSD3

dependencies:
- attoparsec # can help when implementing the RESP parser
- base >= 4.7 && < 5
- bytestring
- containers
- network
- stm
- time # useful in the expiry stage

executables:
  hs-redis-clone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
